version: '3.3'

services:
  jenkins:
    build:
      context: jenkins/
      args:
        JENKINS_VERSION: $JENKINS_VERSION
    container_name: jenkins_docker
    # user uid:gid
    user: root
    privileged: true    
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
        # enable persistent volume (warning: make sure that the local jenkins_home folder is created)
        - jenkins_home:/var/jenkins_home
        # mount docker sock and binary for docker in docker (only works on linux)
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker  

volumes:
  jenkins_home:
    external: true
